name: k_auth_example
description: K-Auth example app
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  k_auth:
    path: ../
  # 통합 예제용 (선택)
  dio: ^5.4.0
  flutter_riverpod: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
